#!/usr/bin/env bash
#
# Copyright (C) 2022 Vaticle
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# TypeDB global variables
JAVA_BIN=java
if [[ ! -z "$JAVA_HOME" ]]; then
    JAVA_BIN="$JAVA_HOME/bin/java"
fi
[[ $(readlink $0) ]] && path=$(readlink $0) || path=$0
TYPEDB_HOME=$(cd "$(dirname "${path}")" && pwd -P)

TYPEDB_SERVER_DIR="${TYPEDB_HOME}/server"

SERVER_PRESENT=$([[ -d "$TYPEDB_SERVER_DIR" ]] && echo yes)
CONSOLE_PRESENT=$([[ -d "${TYPEDB_HOME}/console" ]] && echo yes)

# ================================================
# common helper functions
# ================================================
exit_if_java_not_found() {
    which "${JAVA_BIN}" > /dev/null
    exit_code=$?

    if [[ $exit_code -ne 0 ]]; then
        echo "Java is not installed on this machine. TypeDB needs Java 11+ in order to run."
        exit 1
    fi
}

print_usage() {
    if [[ $SERVER_PRESENT ]]; then
        echo "  Server:          typedb server [--help]"
    fi
    if [[ $CONSOLE_PRESENT ]]; then
        echo "  Console:         typedb console [--help]"
    fi
}

# =============================================
# main routine
# =============================================

exit_if_java_not_found

if [[ ! $SERVER_PRESENT && ! $CONSOLE_PRESENT ]]; then
    echo "TypeDB Console and Server are not installed!"
    exit 1

else case "$1" in
    console)
        if [[ ! $CONSOLE_PRESENT ]]; then
            echo "TypeDB Console not found. Make sure to install or download TypeDB Console."
            exit 1
        fi

        SERVICE_LIB_CP="console/lib/*"
        CLASSPATH="${TYPEDB_HOME}/${SERVICE_LIB_CP}:${TYPEDB_HOME}/console/conf/"
        # exec replaces current shell process with java so no commands after this one will ever get executed
        exec ${JAVA_BIN} ${JAVAOPTS} -cp "${CLASSPATH}" -Dtypedb.dir="${TYPEDB_HOME}" com.vaticle.typedb.console.TypeDBConsole "${@:2}"
        ;;

    server)
        if [[ ! $SERVER_PRESENT ]]; then
            echo "TypeDB Server not found. Make sure to install or download TypeDB."
            exit 1
        fi

        TYPEDB_SERVER_LIB_DIR="${TYPEDB_SERVER_DIR}/lib"
        TYPEDB_CLOUD_SERVER_JAR=("${TYPEDB_SERVER_LIB_DIR}"/com-vaticle-typedb-typedb-cloud-server-*.jar)

        if [[ -f "$TYPEDB_CLOUD_SERVER_JAR" ]]; then
            TYPEDB_SERVER_CLASS=com.vaticle.typedb.cloud.server.TypeDBCloudServer
        else
            TYPEDB_SERVER_CLASS=com.vaticle.typedb.core.server.TypeDBServer
        fi

        IDX=0
        EXTRA_OPTS=
        while [[ "${@:IDX}" ]]; do
            case ${@:IDX:1} in
                --debug) EXTRA_OPTS=-ea
                break;
            esac
            IDX=$((IDX+1))
        done

        CLASSPATH="${TYPEDB_SERVER_DIR}/conf/:${TYPEDB_SERVER_LIB_DIR}/*"

        # exec replaces current shell process with java so no commands after these ones will ever get executed
        exec ${JAVA_BIN} ${JAVAOPTS} ${EXTRA_OPTS} -cp "${CLASSPATH}" -Dtypedb.dir="${TYPEDB_HOME}" ${TYPEDB_SERVER_CLASS} "${@:2}"
        ;;

    "")
        echo "Missing argument. Possible commands are:"
        print_usage
        exit 1
        ;;
    *)
        echo "Invalid argument: $1. Possible commands are: "
        print_usage
        exit 1
        ;;
    esac
fi
