java_library(
    name = "lib",
    srcs = glob(["*.java", "**/*.java"]),
    tags = ["maven_coordinates=io.grakn.cluster:concurrent-actor-lib:{pom_version}"],
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
